import type { Listing } from '@/types'

const OFFICE = {
  id: 'o1',
  slug: 'high5-emlak',
  name: 'HIGH5 EMLAK',
  phone: '+90 256 614 32 10',
  email: 'info@high5emlak.com',
  address: 'Atatürk Bulv. No:48, Merkez',
  city: 'Kuşadası',
  licenseNo: '2024-TDS-001',
  isVerified: true,
  status: 'ACTIVE' as const,
  agents: [],
  createdAt: new Date('2023-01-01'),
}

const AGENT = {
  id: 'a1',
  name: 'Murat Demir',
  avatar: '',
  phone: '+90 532 441 87 23',
  email: 'murat@high5emlak.com',
  officeId: 'o1',
}

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    slug: 'bodrum-satilik-deniz-manzarali-villa',
    title: 'Deniz Manzaralı Lüks Villa',
    description: `Bodrum Yalıkavak'ın en prestijli konumlarından birinde, eşsiz deniz manzarasına sahip bu özel villa, modern mimari ile geleneksel Bodrum ruhunu harmanlıyor. 420 metrekarelik kullanım alanı, geniş teras ve özel havuzuyla ayrıcalıklı bir yaşam sunuyor.\n\nAnfili bahçe katında açık mutfak ve geniş oturma alanı, üst katta ise dört yatak odası bulunuyor. Her odadan deniz manzarası görülüyor. Akıllı ev sistemi, ısıtmalı havuz, otomatik sulama ve güvenlik kameralarıyla donatılmış.\n\nYalıkavak marinasına 800 metre yürüme mesafesinde, restoranlar ve butik mağazalara yakın. Yatırım veya birinci konut olarak ideal.`,
    price: 85_000_000,
    currency: 'TRY',
    listingType: 'SALE',
    propertyType: 'VILLA',
    status: 'ACTIVE',
    city: 'Muğla',
    district: 'Bodrum',
    neighborhood: 'Yalıkavak',
    sqm: 420,
    rooms: '5+2',
    bathrooms: 4,
    floors: 2,
    buildingFloor: 0,
    age: 3,
    viewType: 'SEA',
    hasPool: true,
    hasGarage: true,
    hasGarden: true,
    isFurnished: true,
    images: [],
    agent: AGENT,
    office: OFFICE,
    isRadar: true,
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-04-01'),
  },
  {
    id: '2',
    slug: 'kusadasi-satilik-sehir-manzarali-31-daire',
    title: 'Şehir Manzaralı 3+1 Daire',
    description: `Kuşadası Kadınlar Denizi bölgesinde, şehir ve deniz manzaralı bu 3+1 daire, 2020 yapımı güvenlikli sitede yer almaktadır. Güneşe karşı konumu, geniş balkonu ve kaliteli malzemeleriyle öne çıkıyor.\n\nYüksek tavanlı geniş salon, açık mutfak ve üç yatak odasıyla aileler için ideal. Bina içinde havuz, spor salonu ve kapalı otopark mevcut.\n\nKadınlar Denizi plajına 400 metre, Kuşadası merkezine 5 dakika. Yıl boyu kullanıma uygun.`,
    price: 32_000_000,
    currency: 'TRY',
    listingType: 'SALE',
    propertyType: 'APARTMENT',
    status: 'ACTIVE',
    city: 'Aydın',
    district: 'Kuşadası',
    neighborhood: 'Kadınlar Denizi',
    sqm: 145,
    rooms: '3+1',
    bathrooms: 2,
    floors: 8,
    buildingFloor: 5,
    age: 6,
    viewType: 'SEA',
    hasPool: true,
    hasGarage: true,
    hasGarden: false,
    isFurnished: false,
    images: [],
    agent: AGENT,
    office: OFFICE,
    createdAt: new Date('2026-03-20'),
    updatedAt: new Date('2026-04-02'),
  },
  {
    id: '3',
    slug: 'cesme-kiralik-denize-sifir-21-daire',
    title: 'Denize Sıfır 2+1 Kiralık Daire',
    description: `Çeşme Alaçatı'nın kalbinde, denize sıfır konumda 2+1 kiralık daire. Taş ev mimarisi korunarak restore edilmiş, otantik Ege atmosferini yansıtıyor.\n\nAçık mutfak, ferah oturma alanı ve deniz manzaralı teras. Yaz sezonu kısa dönem veya yıllık kiralama seçeneği mevcut. Evcil hayvan kabul edilmemektedir.\n\nAlaçatı çarşısına yürüme mesafesinde, plaja 50 metre.`,
    price: 75_000,
    currency: 'TRY',
    listingType: 'RENT',
    propertyType: 'APARTMENT',
    status: 'ACTIVE',
    city: 'İzmir',
    district: 'Çeşme',
    neighborhood: 'Alaçatı',
    sqm: 95,
    rooms: '2+1',
    bathrooms: 1,
    floors: 2,
    buildingFloor: 1,
    age: 15,
    viewType: 'SEA',
    hasPool: false,
    hasGarage: false,
    hasGarden: false,
    isFurnished: true,
    images: [],
    agent: AGENT,
    office: OFFICE,
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-04-03'),
  },
  {
    id: '4',
    slug: 'fethiye-satilik-havuzlu-villa',
    title: 'Havuzlu Deniz Manzaralı Villa',
    description: `Fethiye Ölüdeniz'in eşsiz mavi lagününe tepeden bakan bu olağanüstü villa, 580 metrekare üzerine inşa edilmiş. Panoramik deniz manzarası, iki katlı özel havuzu ve geniş bahçesiyle Türkiye'nin en gözde tatil bölgesinde benzersiz bir yaşam sunuyor.\n\nAlt katta açık plan yaşam alanı, büyük mutfak ve misafir dairesi; üst katta beş yatak odası, her birinde özel banyo. Özel bahçede ızgara alanı, oturma terası ve yüzme havuzu.\n\nÖlüdeniz plajına 10 dakika, Fethiye merkezine 15 dakika.`,
    price: 120_000_000,
    currency: 'TRY',
    listingType: 'SALE',
    propertyType: 'VILLA',
    status: 'ACTIVE',
    city: 'Muğla',
    district: 'Fethiye',
    neighborhood: 'Ölüdeniz',
    sqm: 580,
    rooms: '6+2',
    bathrooms: 5,
    floors: 2,
    buildingFloor: 0,
    age: 7,
    viewType: 'SEA',
    hasPool: true,
    hasGarage: true,
    hasGarden: true,
    isFurnished: true,
    images: [],
    agent: AGENT,
    office: OFFICE,
    isRadar: true,
    createdAt: new Date('2026-03-10'),
    updatedAt: new Date('2026-03-30'),
  },
  {
    id: '5',
    slug: 'bodrum-satilik-merkezi-21-daire',
    title: 'Merkezi Konumda 2+1 Daire',
    description: `Bodrum merkezinde, yürüme mesafesinde tüm olanaklara ulaşabileceğiniz bu 2+1 daire, akıllı yatırım arayanlar için ideal. 2018 yapımı, bakımlı bina. Pratik plan, balkon ve açık mutfak.\n\nMerkez lokasyonu sayesinde kira getirisi yüksek. Otopark, asansör mevcut.`,
    price: 28_000_000,
    currency: 'TRY',
    listingType: 'SALE',
    propertyType: 'APARTMENT',
    status: 'ACTIVE',
    city: 'Muğla',
    district: 'Bodrum',
    neighborhood: 'Merkez',
    sqm: 110,
    rooms: '2+1',
    bathrooms: 1,
    floors: 5,
    buildingFloor: 3,
    age: 8,
    viewType: 'CITY',
    hasPool: false,
    hasGarage: true,
    hasGarden: false,
    isFurnished: false,
    images: [],
    agent: AGENT,
    office: OFFICE,
    createdAt: new Date('2026-04-01'),
    updatedAt: new Date('2026-04-01'),
  },
  {
    id: '6',
    slug: 'antalya-satilik-ticari-alan',
    title: 'Merkezi Ticari Alan',
    description: `Antalya Lara'nın ana caddesinde, yüksek yaya trafiğine sahip bu ticari alan, restoran, mağaza veya ofis kullanımına uygun. Geniş cam cephe, yüksek tavan, arka depo alanı.`,
    price: 15_000_000,
    currency: 'TRY',
    listingType: 'SALE',
    propertyType: 'COMMERCIAL',
    status: 'ACTIVE',
    city: 'Antalya',
    district: 'Muratpaşa',
    neighborhood: 'Lara',
    sqm: 240,
    floors: 1,
    buildingFloor: 0,
    age: 12,
    viewType: 'CITY',
    images: [],
    agent: AGENT,
    office: OFFICE,
    createdAt: new Date('2026-03-05'),
    updatedAt: new Date('2026-03-25'),
  },
  {
    id: '7',
    slug: 'izmir-kiralik-modern-11-daire',
    title: 'Modern Stüdyo Daire',
    description: `İzmir Alsancak'ta, şehrin en canlı semtinde modern stüdyo daire. Tam mobilyalı, beyaz eşyalı, tüm giderleri kira dahilinde. Yürüyüş mesafesinde metro, restoran ve sahil.\n\nKısa ve uzun dönem kiralama imkânı.`,
    price: 45_000,
    currency: 'TRY',
    listingType: 'RENT',
    propertyType: 'APARTMENT',
    status: 'ACTIVE',
    city: 'İzmir',
    district: 'Konak',
    neighborhood: 'Alsancak',
    sqm: 60,
    rooms: '1+1',
    bathrooms: 1,
    floors: 6,
    buildingFloor: 4,
    age: 2,
    viewType: 'CITY',
    hasPool: false,
    hasGarage: false,
    hasGarden: false,
    isFurnished: true,
    images: [],
    agent: AGENT,
    office: OFFICE,
    createdAt: new Date('2026-04-03'),
    updatedAt: new Date('2026-04-03'),
  },
  {
    id: '8',
    slug: 'marmaris-satilik-marine-manzarali-villa',
    title: 'Marine Manzaralı Özel Villa',
    description: `Marmaris İçmeler'de, marinaya bakan bu özel villa, kaliteli malzeme ve işçiliğiyle öne çıkıyor. 4+2 planı, ısıtmalı özel havuz, çift garaj ve bakımlı Akdeniz bahçesi.\n\nYat limanına 300 metre, İçmeler plajına 200 metre. Tam mobilyalı, kiralık gelir potansiyeli yüksek.`,
    price: 95_000_000,
    currency: 'TRY',
    listingType: 'SALE',
    propertyType: 'VILLA',
    status: 'ACTIVE',
    city: 'Muğla',
    district: 'Marmaris',
    neighborhood: 'İçmeler',
    sqm: 380,
    rooms: '4+2',
    bathrooms: 3,
    floors: 2,
    buildingFloor: 0,
    age: 5,
    viewType: 'SEA',
    hasPool: true,
    hasGarage: true,
    hasGarden: true,
    isFurnished: true,
    images: [],
    agent: AGENT,
    office: OFFICE,
    createdAt: new Date('2026-03-18'),
    updatedAt: new Date('2026-04-02'),
  },
  {
    id: '9',
    slug: 'alanya-satilik-deniz-manzarali-daire',
    title: 'Deniz Manzaralı 2+1 Daire',
    description: `Alanya Mahmutlar'da, deniz manzaralı güneşli 2+1 daire. Güvenlikli sitede havuz, tenis kortu ve çocuk oyun alanı. Antalya havalimanına 90 km, alışveriş merkezi ve plaja yürüme mesafesi.\n\nEkonomik fiyatıyla Türkiye'nin Akdeniz kıyısına yatırım yapmak isteyenler için mükemmel fırsat.`,
    price: 18_000_000,
    currency: 'TRY',
    listingType: 'SALE',
    propertyType: 'APARTMENT',
    status: 'ACTIVE',
    city: 'Antalya',
    district: 'Alanya',
    neighborhood: 'Mahmutlar',
    sqm: 90,
    rooms: '2+1',
    bathrooms: 1,
    floors: 10,
    buildingFloor: 7,
    age: 10,
    viewType: 'SEA',
    hasPool: true,
    hasGarage: false,
    hasGarden: false,
    isFurnished: false,
    images: [],
    agent: AGENT,
    office: OFFICE,
    createdAt: new Date('2026-03-25'),
    updatedAt: new Date('2026-04-01'),
  },
  {
    id: '10',
    slug: 'didim-satilik-tarla',
    title: 'Didim Altınkum Yatırımlık Arsa',
    description: `Didim Altınkum'da, belediye hizmetleri içinde, imarlı yatırımlık arsa. Turizm bölgesinde konumuyla villa veya tatil konutu inşaatı için ideal. Altyapı hazır, tapu temiz.\n\nAltınkum plajına 1 km, Didim merkeze 5 km.`,
    price: 8_000_000,
    currency: 'TRY',
    listingType: 'SALE',
    propertyType: 'LAND',
    status: 'ACTIVE',
    city: 'Aydın',
    district: 'Didim',
    neighborhood: 'Altınkum',
    sqm: 1200,
    viewType: 'NONE',
    images: [],
    agent: AGENT,
    office: OFFICE,
    createdAt: new Date('2026-02-20'),
    updatedAt: new Date('2026-03-10'),
  },
  {
    id: '11',
    slug: 'kusadasi-kiralik-villa',
    title: 'Kuşadası Tatil Villası',
    description: `Kuşadası Güzelçamlı'da, özel havuzlu ve bakımlı bahçeli tatil villası. Haftalık veya aylık kiralama seçeneğiyle. 4+1 plan, tam mobilyalı, klimalı tüm odalar.\n\nMilli Park girişine 2 km, Güzelçamlı plajına 1 km.`,
    price: 150_000,
    currency: 'TRY',
    listingType: 'RENT',
    propertyType: 'VILLA',
    status: 'ACTIVE',
    city: 'Aydın',
    district: 'Kuşadası',
    neighborhood: 'Güzelçamlı',
    sqm: 280,
    rooms: '4+1',
    bathrooms: 3,
    floors: 2,
    buildingFloor: 0,
    age: 8,
    viewType: 'NATURE',
    hasPool: true,
    hasGarage: false,
    hasGarden: true,
    isFurnished: true,
    images: [],
    agent: AGENT,
    office: OFFICE,
    createdAt: new Date('2026-04-05'),
    updatedAt: new Date('2026-04-05'),
  },
  {
    id: '12',
    slug: 'bodrum-satilik-luks-penthouse',
    title: 'Lüks Penthouse Daire',
    description: `Bodrum Türkbükü'nün en seçkin adreslerinden birinde, özel terasıyla 200 metrekarelik lüks penthouse. Geniş deniz ve doğa manzarası, kışlık cam balkon, jakuzili banyo.\n\nTürkbükü koyuna yürüme mesafesinde, restoran ve marinaya yakın. Özel park yeri ve depo dahil.`,
    price: 45_000_000,
    currency: 'TRY',
    listingType: 'SALE',
    propertyType: 'APARTMENT',
    status: 'ACTIVE',
    city: 'Muğla',
    district: 'Bodrum',
    neighborhood: 'Türkbükü',
    sqm: 200,
    rooms: '3+1',
    bathrooms: 2,
    floors: 6,
    buildingFloor: 6,
    age: 4,
    viewType: 'SEA',
    hasPool: true,
    hasGarage: true,
    hasGarden: false,
    isFurnished: true,
    images: [],
    agent: AGENT,
    office: OFFICE,
    isRadar: true,
    createdAt: new Date('2026-04-06'),
    updatedAt: new Date('2026-04-06'),
  },
]
